- id: authz-schema-sync-check
  name: Check SpiceDB schema and resources sync
  description: Validates that output files are in sync with schema.zed
  entry: authz-schema-sync-check
  language: python
  files: '\.zed$|\.py$|\.ts$'
